Add Alma and Rocky Linux as supported host OSes
openshift-metal3/dev-scripts pull request #1348
Opened 2022-02-03 17:53 UTC by cybertron

These two distributions are essentially what CentOS was pre-Stream,
so they should generally be compatible as well. They are documented
as "best effort" support though since I don't think we'll be running
them in CI.

2022-02-03 17:56 UTC, cybertron commented
/hold

This got it past the validation stage, but something failed later on. Looks like I need to make further changes.

2022-02-03 18:02 UTC, andfasano commented
Note that the default packet setup step creates an instance with Centos8.
If you want something else, you'll need at least a temporary test where you could set the [`PACKET_OS` variable](https://github.com/openshift/release/blob/cb80be4641325733af23c5b7320e92e068f1184d/ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-ref.yaml#L16) as required

2022-03-22 21:07 UTC, cybertron commented
Okay, this one is working for me locally on Alma. Had to get a little hacky with the ansible python interpreter, but that should be a temporary thing until Ansible fixes it properly.

/hold cancel

2022-04-04 15:05 UTC, cybertron commented
/retest-required

2022-04-05 07:49 UTC, elfosardo commented
/retest

2022-04-05 07:51 UTC, elfosardo requested changes

2022-04-05 07:51 UTC, elfosardo commented on 01_install_requirements.sh
> +    if [[ $DISTRO == "centos8" ]]; then
let's move this before L37 ?

2022-04-07 20:13 UTC, cybertron commented on 01_install_requirements.sh
> +    if [[ $DISTRO == "centos8" ]]; then
Done

2022-06-02 15:30 UTC, cybertron commented
/retest-required

2022-06-14 20:39 UTC, cybertron commented
/retest-required

2022-06-16 15:10 UTC, cybertron commented
/retest

Some of these jobs are no longer required, and I think all of the required ones have passed.

2022-06-24 17:16 UTC, cybertron commented
/retest-required

Looks like issues getting a test environment.

2022-07-21 13:00 UTC, danwinship commented
any reason this hasn't merged? CentOS 8 on Equinix no longer seems to work for me:

```
[root@dwinship ~]# dnf -y install git jq make
CentOS Linux 8 - AppStream                                            1.5 kB/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

2022-07-21 13:40 UTC, danwinship commented
hm... nor does Rocky even with this PR:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ansible.posix.selinux_payload_btu2jecb/ansible_ansible.posix.selinux_payload.zip/ansible_collections/ansible/posix/plugins/modules/selinux.py", line 100, in <module>
ModuleNotFoundError: No module named 'selinux'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "configfile": "/etc/selinux/config",
            "policy": "targeted",
            "state": "permissive",
            "update_kernel_param": false
        }
    },
    "msg": "Failed to import the required Python library (libselinux-python) on dwinship's Python /bin/python3.9. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}
```

`python3-libselinux` is installed though...

2022-07-21 19:51 UTC, cybertron commented
Ah, that sounds like the same problem I ran into with Alma. Maybe the Python interpreter workaround is needed for Rocky too. I thought someone had already fixed that for Rocky but maybe not. I need to rebase this anyway, so I'll add Rocky to the conditional so you can try it.

2022-07-22 09:14 UTC, elfosardo commented
/retest

2022-07-22 11:25 UTC, danwinship commented
> I'll add Rocky to the conditional so you can try it.

I retried using Alma and it worked, and I managed to test what I was testing. I do need to go back and test an updated patch at some point but I'm not sure when I'm going to get to that...

2022-07-23 15:03 UTC, danwinship commented
/lgtm
works with Rocky now too

2022-07-26 09:04 UTC, dtantsur commented
/approve

2022-07-27 14:18 UTC, elfosardo commented
/retest

2022-07-27 16:41 UTC, cybertron commented
/retest-required

Infra failure

2022-08-22 22:07 UTC, cybertron commented
Rebased to account for some recent changes in OS setup.

2022-08-23 16:56 UTC, cybertron commented
/retest

2022-08-24 06:27 UTC, elfosardo commented
/lgtm

2022-08-24 06:32 UTC, merged