Fix python3 setup
openshift-metal3/dev-scripts pull request #1371
Opened 2022-03-28 07:41 UTC by andfasano

2022-03-28 07:42 UTC, andfasano commented
cc @elfosardo

2022-03-29 05:56 UTC, elfosardo commented
/retest

2022-03-29 06:00 UTC, elfosardo requested changes
we should also change the entry in metallb/run_e2e.sh and the "yq install message instruction" in metal3-dev/local-bmo.sh and metal3-dev/local-capbm.sh

2022-03-29 06:00 UTC, elfosardo commented on 01_install_requirements.sh
>  # and lxml for the pyxpath script
maybe also mention the selinux module ?

2022-04-07 08:07 UTC, andfasano commented
> we should also change the entry in metallb/run_e2e.sh and the "yq install message instruction" in metal3-dev/local-bmo.sh and metal3-dev/local-capbm.sh

Ok for metal-3-dev, but metallb has its own owners (@fedepaol)

2022-05-12 20:29 UTC, andfasano commented
/retest-required

2022-05-30 15:25 UTC, elfosardo commented
/retest

2022-05-30 15:25 UTC, elfosardo approved these changes

2023-01-20 16:48 UTC, closed without merging