Fixed docs
openshift-metal3/dev-scripts pull request #1530
Opened 2023-06-01 14:36 UTC by pawanpinjarkar

2023-06-07 07:47 UTC, andfasano commented
/approve

2023-06-07 09:12 UTC, dtantsur requested changes
Highlighting my request above.

2023-06-08 13:56 UTC, pawanpinjarkar commented
> Highlighting my request above.

Done

2023-06-15 11:32 UTC, bfournie commented
/lgtm

2023-06-15 11:34 UTC, merged