arm64 needs devel packages for lxml install
openshift-metal3/dev-scripts pull request #1549
Opened 2023-07-10 15:15 UTC by sgoveas

ipi jobs fail installing lxml as it needs python39 libxml2 and libxslt devel packages

2023-07-12 09:35 UTC, dtantsur commented on 01_install_requirements.sh
> +[[ $GOARCH == "aarch64" ]] && dnf -y install python39-devel libxml2-devel libxslt-devel
Missing sudo

2023-08-01 16:13 UTC, dtantsur commented
/ok-to-test
/lgtm

2023-08-01 18:15 UTC, sgoveas commented on 01_install_requirements.sh
> +[[ $GOARCH == "aarch64" ]] && sudo dnf -y install python39-devel libxml2-devel libxslt-devel
done

2023-08-02 06:56 UTC, elfosardo requested changes

2023-08-02 06:56 UTC, elfosardo commented on 01_install_requirements.sh
> +[[ $GOARCH == "aarch64" ]] && sudo dnf -y install python39-devel libxml2-devel libxslt-devel
doesn't look done :)

2023-08-15 11:23 UTC, sgoveas commented
/retest

2023-08-31 20:28 UTC, sgoveas commented
/retest-required

2023-09-01 11:04 UTC, sgoveas commented
/retest

2023-09-01 11:19 UTC, sgoveas commented
/test e2e-metal-ipi-serial-ipv4

2023-09-04 10:07 UTC, derekhiggins commented
/retest-required

2023-09-04 15:24 UTC, sgoveas commented
/retest

2023-09-04 18:09 UTC, sgoveas commented
/retest

2023-09-05 08:33 UTC, derekhiggins commented
/approve

2023-09-07 08:55 UTC, dtantsur commented
/lgtm

2023-09-08 05:31 UTC, sgoveas commented
/test e2e-agent-compact-ipv4

2023-09-08 08:49 UTC, sgoveas commented
/test e2e-agent-compact-ipv4

2023-09-08 14:23 UTC, sgoveas commented
/test e2e-metal-ipi-ovn-ipv6

2023-09-11 08:12 UTC, aleskandro commented
/test e2e-agent-compact-ipv4

2023-09-11 09:26 UTC, sgoveas commented
/test e2e-metal-ipi-bm

2023-09-11 12:10 UTC, merged